### ISSUE TITLE
Dependent packages are not installed automatically

### ISSUE THREAD

**Issue by andrei-shabanski** [spothero/py-responsys#11]
I installed `responsys_client` and tried to use this package, but I got an error:

```python
>>> import responsys_client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andrei/.pyenv/versions/py-responsys-2.7/lib/python2.7/site-packages/responsys_client/__init__.py", line 1, in <module>
    from .client import ResponsysClient
  File "/home/andrei/.pyenv/versions/py-responsys-2.7/lib/python2.7/site-packages/responsys_client/client.py", line 6, in <module>
    import pytz
ImportError: No module named pytz
```

The reason for the error is that the dependent packages were not installed. 

I've created a pull request to fix it https://github.com/spothero/py-responsys/pull/10

**Comment by nbkincaid** [comment]
@andrei-shabanski Excellent, thank you for this, I've merged your pr.
